version: "3"

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./sandbox:/usr/src/sandbox
    command: yarn start
    ports:
      - "3000:3000"
    tty: true
